### ISSUE TITLE
Support LIMIT OPTION for SQL SELECT QUERY

### ISSUE THREAD

**Issue by alanrigele** [adjust/clickhouse_fdw#28] opened 2020-02-07 13:56 UTC
When executing the following SQL in postgres 

select * from ran.ids limit 100;

QUERY PLAN                                                   |
-------------------------------------------------------------|
Limit  (cost=0.00..0.00 rows=1 width=128)                    |
  ->  Foreign Scan on ids  (cost=0.00..0.00 rows=0 width=128)|

The following will be passed down to Clickhouse to perform
SELECT vendor, node, "nodeType", "ID" FROM "RAN"."IDs

The "LIMIT 100" query option is not past 
This causes the server to provide the full data set to the client, which is not requested

Clickhouse log

2020.02.07 07:46:50.890220 [ 832 ] {} <Debug> TCPHandler: Connected ClickHouse client version 1.1.0, revision: 54126, database: RAN, user: ran_user.
2020.02.07 07:46:50.891945 [ 832 ] {43b66dc7-cbee-4cd6-bef9-2507818ea23b} <Debug> executeQuery: (from 172.28.247.16:51884, user: ran_user) **SELECT vendor, node, "nodeType", "ID" FROM "RAN"."IDs"**
2020.02.07 07:46:50.892903 [ 832 ] {43b66dc7-cbee-4cd6-bef9-2507818ea23b} <Debug> RAN.IDs (SelectExecutor): Key condition: unknown
2020.02.07 07:46:50.892956 [ 832 ] {43b66dc7-cbee-4cd6-bef9-2507818ea23b} <Debug> RAN.IDs (SelectExecutor): Selected 1 parts by date, 1 parts by key, 1537 marks to read from 1 ranges
2020.02.07 07:46:50.895235 [ 832 ] {43b66dc7-cbee-4cd6-bef9-2507818ea23b} <Debug> executeQuery: Query pipeline:
Union
 Expression × 32
  Expression
   MergeTreeThread

2020.02.07 07:46:50.908439 [ 31 ] {} <Debug> DiskSpaceMonitor: Reserving 1.00 MiB on disk `default`, having unreserved 2.92 TiB.
2020.02.07 07:46:50.912089 [ 16 ] {} <Debug> system.trace_log (MergerMutator): Selected 3 parts from 202002_70208_70208_0 to 202002_70210_70210_0
2020.02.07 07:46:50.912305 [ 16 ] {} <Debug> DiskSpaceMonitor: Reserving 1.00 MiB on disk `default`, having unreserved 2.92 TiB.
2020.02.07 07:46:50.912373 [ 16 ] {} <Debug> system.trace_log (MergerMutator): Merging 3 parts: from 202002_70208_70208_0 to 202002_70210_70210_0 into tmp_merge_202002_70208_70210_1
2020.02.07 07:46:50.913084 [ 16 ] {} <Debug> system.trace_log (MergerMutator): Selected MergeAlgorithm: Horizontal
2020.02.07 07:46:50.917649 [ 16 ] {} <Debug> system.trace_log (MergerMutator): Merge sorted 518 rows, containing 7 columns (7 merged, 0 gathered) in 0.01 sec., 98466.68 rows/sec., 14.03 MB/sec.
2020.02.07 07:46:58.412786 [ 31 ] {} <Debug> DiskSpaceMonitor: Reserving 1.00 MiB on disk `default`, having unreserved 2.92 TiB.
2020.02.07 07:47:03.976250 [ 832 ] {43b66dc7-cbee-4cd6-bef9-2507818ea23b} <Information> executeQuery: Read 12531115 rows, 2.10 GiB in 13.084 sec., 957733 rows/sec., 164.20 MiB/sec.
2020.02.07 07:47:03.976336 [ 832 ] {43b66dc7-cbee-4cd6-bef9-2507818ea23b} <Debug> MemoryTracker: Peak memory usage (for query): 257.36 MiB.
2020.02.07 07:47:03.978453 [ 832 ] {43b66dc7-cbee-4cd6-bef9-2507818ea23b} <Debug> MemoryTracker: Peak memory usage (total): 257.36 MiB.
2020.02.07 07:47:03.978522 [ 832 ] {43b66dc7-cbee-4cd6-bef9-2507818ea23b} <Information> TCPHandler: Processed in 13.088 sec.
2020.02.07 07:47:05.915827 [ 31 ] {} <Debug> DiskSpaceMonitor: Reserving 1.00 MiB on disk `default`, having unreserved 2.92

**Comment by mkabilov** [comment] 2020-02-07 13:58
Duplicate of https://github.com/adjust/clickhouse_fdw/issues/8

**Closed by mkabilov** 2020-02-07 13:58 UTC
