### ISSUE TITLE
communication error: No URL set!

### ISSUE THREAD

**Issue by ELDIABLO4400** [adjust/clickhouse_fdw#5] opened 2019-08-01 20:42 UTC
After installation clickhouse_fdw i try to make example from "usage" part in Readme, but when i make: "SELECT bbl,tbea,bav,insertion_date FROM tax_bills_nyc LIMIT 5;"
postgres recive:
clickhouse_fdw: communication error: No URL set!

Where I wrong?

**Comment by ildus** [comment] 2019-08-02 06:36
hi, I think you somehow removed `host` option. Try:

    alter server clickhouse_svr options (set host '127.0.0.1', set port '8123');

**Comment by ELDIABLO4400** [comment] 2019-08-02 08:14
When i try to execute:
alter server clickhouse_svr options (set host '127.0.0.1', set port '8123');
i recieve: "option "port" not found"

Then i try: alter server clickhouse_svr options (set host '127.0.0.1');
But result clickhouse_fdw: communication error: No URL set! not change.

**Comment by ildus** [comment] 2019-08-02 08:39
Ok, it means that you didn't specify it, then just run:

    alter server clickhouse_svr options (set host '127.0.0.1');

**Comment by ildus** [comment] 2019-08-02 08:44
It should work after set the host. I would suggest you to recreate it, and just skip host option, like this:

    CREATE SERVER clickhouse_svr FOREIGN DATA WRAPPER clickhouse_fdw
	OPTIONS(dbname 'test_database');

**Comment by ELDIABLO4400** [comment] 2019-08-02 08:54
I recreate clickhouse_svr with skip host option;
When i execute select command, i recieve
clickhouse_fdw: communication error: No URL set!

**Comment by ildus** [comment] 2019-08-02 09:40
Ok. Could you provide exact script you running? Also I need version of your postgres and operation system details. I have just tried command from 'usage' section, and all is working on my system, so you I need steps from you to reproduce the issue.

**Comment by ELDIABLO4400** [comment] 2019-08-02 10:47
CentOS release 6.9 (Final)
PostgreSQL 11.4 on x86_64-pc-linux-gnu
ClickHouse client version 19.9.5.36.
gcc (GCC) 9.1.0
cmake version 3.15.1
curl 7.65.3-DEV (Linux) libcurl/7.65.3-DEV

Install process (in unpacking directory from root):
mkdir build
cd build
cmake ..
make
make install

Then in clickhouse (I use tabix):
CREATE DATABASE test_database;
USE test_database;
CREATE TABLE tax_bills_nyc
(
    bbl Int64,
    owner_name String,
    address String,
    tax_class String,
    tax_rate String,
    emv Float64,
    tbea Float64,
    bav Float64,
    tba String,
    property_tax String,
    condonumber String,
    condo String,
    insertion_date DateTime MATERIALIZED now()
)
ENGINE = MergeTree PARTITION BY tax_class ORDER BY (owner_name);

curl -X GET 'http://taxbills.nyc/tax_bills_june15_bbls.csv' | clickhouse-client --input_format_allow_errors_num=10 --query="INSERT INTO test_database.tax_bills_nyc FORMAT CSV"

I check this state, 
Data is download normally.
![image](https://user-images.githubusercontent.com/53582622/62365092-d7c8e800-b52b-11e9-90f1-b36f27f87d1c.png)


Then in postgres:
CREATE EXTENSION clickhouse_fdw;
CREATE SERVER clickhouse_svr FOREIGN DATA WRAPPER clickhouse_fdw OPTIONS(dbname 'test_database');
CREATE USER MAPPING FOR CURRENT_USER SERVER clickhouse_svr;
CREATE FOREIGN TABLE tax_bills_nyc
(
    bbl int8,
    owner_name text,
    address text,
    tax_class text,
    tax_rate text,
    emv Float,
    tbea Float,
    bav Float,
    tba text,
    property_tax text,
    condonumber text,
    condo text,
    insertion_date Time
) SERVER clickhouse_svr OPTIONS (table_name 'tax_bills_nyc');

At this point all commands execute normally.

SELECT bbl,tbea,bav,insertion_date FROM tax_bills_nyc LIMIT 5;
ERROR:  clickhouse_fdw: communication error: No URL set!

**Comment by ELDIABLO4400** [comment] 2019-08-02 10:56
Now i try use:
REATE SERVER clickhouse_svr FOREIGN DATA WRAPPER clickhouse_fdw OPTIONS(dbname 'test_database', host '127.0.0.1', port '8123');
but result not changed

**Comment by ildus** [comment] 2019-08-02 11:56
Could you show output of `select * from pg_user_mappings;`? User mapping has priority on server options.

**Comment by ELDIABLO4400** [comment] 2019-08-02 12:08
select * from pg_user_mappings;
 umid  | srvid |    srvname     | umuser | usename | umoptions 
-------+-------+----------------+--------+---------+-----------
 20629 | 20628 | clickhouse_svr |  16386 | admin   | 
(1 row)

**Comment by ildus** [comment] 2019-08-02 12:40
I simplified the http connection procedure, please try to recompile and install new version.

**Comment by ELDIABLO4400** [comment] 2019-08-02 14:35
After reinstall with your changes, this work fine.

Purely for myself, what was the problem?
By code, you stopped using * url, curl_url().
Is it a matter of libcurl or curl?

Thank you very much!!!

**Comment by ildus** [comment] 2019-08-02 15:45
I think the problem was that I set the actual url after `curl_easy_setopt`. There is a chance that moving it after url construction would solve the problem, but then I decided to not use `url` object at all.

btw `user` option should be set on user mapping, not server. Also I have removed `hostaddr`, that was legacy of `postgres_fdw`

**Closed** 2019-08-02 15:57 UTC
